In [1]:
import pandas as pd

data = pd.read_csv('2.1 2.csv')
data.head()

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945.00","$33,337.00",3.5,6.0,265.0,17.0,23.0,4451.0,106.0,189.0
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820.00","$21,761.00",2.0,4.0,200.0,24.0,31.0,2778.0,101.0,172.0
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990.00","$24,647.00",2.4,4.0,200.0,22.0,29.0,3230.0,105.0,183.0
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195.00","$30,299.00",3.2,6.0,270.0,20.0,28.0,3575.0,108.0,186.0
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755.00","$39,014.00",3.5,6.0,225.0,18.0,24.0,3880.0,115.0,197.0

In [2]:
# data['Make'] = 'Acura'
# data.head()

In [3]:
'''
Return only Acuras with Horsepower over 250
'''
#data.loc[(data['Make'].isin("Acura")), 'Horsepower'] > 250
data_Make = (data['Make'].isin(["Acura"]))
data_HP = (data['Horsepower'] > 250)
data[data_HP & data_Make]

data["Case"] = 'bad'
data.loc[data_HP & data_Make, "Case"] = 'good'
data

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length,Case
0,Acura,MDX,SUV,Asia,All,"$36,945.00","$33,337.00",3.5,6.0,265.0,17.0,23.0,4451.0,106.0,189.0,good
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820.00","$21,761.00",2.0,4.0,200.0,24.0,31.0,2778.0,101.0,172.0,bad
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990.00","$24,647.00",2.4,4.0,200.0,22.0,29.0,3230.0,105.0,183.0,bad
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195.00","$30,299.00",3.2,6.0,270.0,20.0,28.0,3575.0,108.0,186.0,good
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755.00","$39,014.00",3.5,6.0,225.0,18.0,24.0,3880.0,115.0,197.0,bad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
427,Volvo,C70 LPT convertible 2dr,Sedan,Europe,Front,"$40,565.00","$38,203.00",2.4,5.0,197.0,21.0,28.0,3450.0,105.0,186.0,bad
428,Volvo,C70 HPT convertible 2dr,Sedan,Europe,Front,"$42,565.00","$40,083.00",2.3,5.0,242.0,20.0,26.0,3450.0,105.0,186.0,bad
429,Volvo,S80 T6 4dr,Sedan,Europe,Front,"$45,210.00","$42,573.00",2.9,6.0,268.0,19.0,26.0,3653.0,110.0,190.0,bad
430,Volvo,V40,Wagon,Europe,Front,"$26,135.00","$24,641.00",1.9,4.0,170.0,22.0,29.0,2822.0,101.0,180.0,bad
431,Volvo,XC70,Wagon,Europe,All,"$35,145.00","$33,112.00",2.5,5.0,208.0,20.0,27.0,3823.0,109.0,186.0,bad

In [4]:
data['Invoice'].describe()

count            428
unique           425
top       $19,638.00
freq               2
Name: Invoice, dtype: object

In [5]:
def timestwo(val):
    return val * 2
data2 = data.copy()
data2[['EngineSize', 'Cylinders']] = data[['EngineSize', 'Cylinders']].map(timestwo)
data2

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length,Case
0,Acura,MDX,SUV,Asia,All,"$36,945.00","$33,337.00",7.0,12.0,265.0,17.0,23.0,4451.0,106.0,189.0,good
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820.00","$21,761.00",4.0,8.0,200.0,24.0,31.0,2778.0,101.0,172.0,bad
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990.00","$24,647.00",4.8,8.0,200.0,22.0,29.0,3230.0,105.0,183.0,bad
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195.00","$30,299.00",6.4,12.0,270.0,20.0,28.0,3575.0,108.0,186.0,good
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755.00","$39,014.00",7.0,12.0,225.0,18.0,24.0,3880.0,115.0,197.0,bad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
427,Volvo,C70 LPT convertible 2dr,Sedan,Europe,Front,"$40,565.00","$38,203.00",4.8,10.0,197.0,21.0,28.0,3450.0,105.0,186.0,bad
428,Volvo,C70 HPT convertible 2dr,Sedan,Europe,Front,"$42,565.00","$40,083.00",4.6,10.0,242.0,20.0,26.0,3450.0,105.0,186.0,bad
429,Volvo,S80 T6 4dr,Sedan,Europe,Front,"$45,210.00","$42,573.00",5.8,12.0,268.0,19.0,26.0,3653.0,110.0,190.0,bad
430,Volvo,V40,Wagon,Europe,Front,"$26,135.00","$24,641.00",3.8,8.0,170.0,22.0,29.0,2822.0,101.0,180.0,bad
431,Volvo,XC70,Wagon,Europe,All,"$35,145.00","$33,112.00",5.0,10.0,208.0,20.0,27.0,3823.0,109.0,186.0,bad

In [6]:
data

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length,Case
0,Acura,MDX,SUV,Asia,All,"$36,945.00","$33,337.00",3.5,6.0,265.0,17.0,23.0,4451.0,106.0,189.0,good
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820.00","$21,761.00",2.0,4.0,200.0,24.0,31.0,2778.0,101.0,172.0,bad
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990.00","$24,647.00",2.4,4.0,200.0,22.0,29.0,3230.0,105.0,183.0,bad
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195.00","$30,299.00",3.2,6.0,270.0,20.0,28.0,3575.0,108.0,186.0,good
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755.00","$39,014.00",3.5,6.0,225.0,18.0,24.0,3880.0,115.0,197.0,bad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
427,Volvo,C70 LPT convertible 2dr,Sedan,Europe,Front,"$40,565.00","$38,203.00",2.4,5.0,197.0,21.0,28.0,3450.0,105.0,186.0,bad
428,Volvo,C70 HPT convertible 2dr,Sedan,Europe,Front,"$42,565.00","$40,083.00",2.3,5.0,242.0,20.0,26.0,3450.0,105.0,186.0,bad
429,Volvo,S80 T6 4dr,Sedan,Europe,Front,"$45,210.00","$42,573.00",2.9,6.0,268.0,19.0,26.0,3653.0,110.0,190.0,bad
430,Volvo,V40,Wagon,Europe,Front,"$26,135.00","$24,641.00",1.9,4.0,170.0,22.0,29.0,2822.0,101.0,180.0,bad
431,Volvo,XC70,Wagon,Europe,All,"$35,145.00","$33,112.00",2.5,5.0,208.0,20.0,27.0,3823.0,109.0,186.0,bad

In [29]:
#Get the average invoice by make

data.groupby(['Origin','Make']).agg({'Horsepower': 'mean'})

dataclean = data.copy()

dataclean['Invoice'] =dataclean['Invoice'].str.replace('$', "")
dataclean['Invoice'] =dataclean['Invoice'].str.replace(',', "")

dataclean['Invoice'] = dataclean['Invoice'].astype(float)
dataclean['Invoice'] = dataclean['Invoice'].round()
dataclean.groupby(['Make']).agg({('Invoice'): 'mean'})

ValueError: Columns must be same length as key